package com.kt.apps.core.utils;

import android.util.SparseArray;
import com.google.android.gms.dynamite.descriptors.com.google.android.gms.measurement.dynamite.ModuleDescriptor;

/* loaded from: classes2.dex */
public final class KeyCodeTranslator {
    public static final KeyCodeTranslator INSTANCE;
    private static final SparseArray<String> map;

    static {
        KeyCodeTranslator keyCodeTranslator = new KeyCodeTranslator();
        INSTANCE = keyCodeTranslator;
        SparseArray<String> sparseArray = new SparseArray<>();
        keyCodeTranslator.addKeyAndValue(sparseArray, "UNKNOWN", 0);
        keyCodeTranslator.addKeyAndValue(sparseArray, "SOFT LEFT", 1);
        keyCodeTranslator.addKeyAndValue(sparseArray, "SOFT RIGHT", 2);
        keyCodeTranslator.addKeyAndValue(sparseArray, "HOME", 3);
        keyCodeTranslator.addKeyAndValue(sparseArray, "BACK", 4);
        keyCodeTranslator.addKeyAndValue(sparseArray, "CALL", 5);
        keyCodeTranslator.addKeyAndValue(sparseArray, "ENDCALL", 6);
        keyCodeTranslator.addKeyAndValue(sparseArray, "0", 7);
        keyCodeTranslator.addKeyAndValue(sparseArray, "1", 8);
        keyCodeTranslator.addKeyAndValue(sparseArray, "2", 9);
        keyCodeTranslator.addKeyAndValue(sparseArray, "3", 10);
        keyCodeTranslator.addKeyAndValue(sparseArray, "4", 11);
        keyCodeTranslator.addKeyAndValue(sparseArray, "5", 12);
        keyCodeTranslator.addKeyAndValue(sparseArray, "6", 13);
        keyCodeTranslator.addKeyAndValue(sparseArray, "7", 14);
        keyCodeTranslator.addKeyAndValue(sparseArray, "8", 15);
        keyCodeTranslator.addKeyAndValue(sparseArray, "9", 16);
        keyCodeTranslator.addKeyAndValue(sparseArray, "STAR", 17);
        keyCodeTranslator.addKeyAndValue(sparseArray, "POUND", 18);
        keyCodeTranslator.addKeyAndValue(sparseArray, "DPAD UP", 19);
        keyCodeTranslator.addKeyAndValue(sparseArray, "DPAD DOWN", 20);
        keyCodeTranslator.addKeyAndValue(sparseArray, "DPAD LEFT", 21);
        keyCodeTranslator.addKeyAndValue(sparseArray, "DPAD RIGHT", 22);
        keyCodeTranslator.addKeyAndValue(sparseArray, "DPAD CENTER", 23);
        keyCodeTranslator.addKeyAndValue(sparseArray, "VOLUME UP", 24);
        keyCodeTranslator.addKeyAndValue(sparseArray, "VOLUME DOWN", 25);
        keyCodeTranslator.addKeyAndValue(sparseArray, "POWER", 26);
        keyCodeTranslator.addKeyAndValue(sparseArray, "CAMERA", 27);
        keyCodeTranslator.addKeyAndValue(sparseArray, "CLEAR", 28);
        keyCodeTranslator.addKeyAndValue(sparseArray, "A", 29);
        keyCodeTranslator.addKeyAndValue(sparseArray, "B", 30);
        keyCodeTranslator.addKeyAndValue(sparseArray, "C", 31);
        keyCodeTranslator.addKeyAndValue(sparseArray, "D", 32);
        keyCodeTranslator.addKeyAndValue(sparseArray, "E", 33);
        keyCodeTranslator.addKeyAndValue(sparseArray, "F", 34);
        keyCodeTranslator.addKeyAndValue(sparseArray, "G", 35);
        keyCodeTranslator.addKeyAndValue(sparseArray, "H", 36);
        keyCodeTranslator.addKeyAndValue(sparseArray, "I", 37);
        keyCodeTranslator.addKeyAndValue(sparseArray, "J", 38);
        keyCodeTranslator.addKeyAndValue(sparseArray, "K", 39);
        keyCodeTranslator.addKeyAndValue(sparseArray, "L", 40);
        keyCodeTranslator.addKeyAndValue(sparseArray, "M", 41);
        keyCodeTranslator.addKeyAndValue(sparseArray, "N", 42);
        keyCodeTranslator.addKeyAndValue(sparseArray, "O", 43);
        keyCodeTranslator.addKeyAndValue(sparseArray, "P", 44);
        keyCodeTranslator.addKeyAndValue(sparseArray, "Q", 45);
        keyCodeTranslator.addKeyAndValue(sparseArray, "R", 46);
        keyCodeTranslator.addKeyAndValue(sparseArray, "S", 47);
        keyCodeTranslator.addKeyAndValue(sparseArray, "T", 48);
        keyCodeTranslator.addKeyAndValue(sparseArray, "U", 49);
        keyCodeTranslator.addKeyAndValue(sparseArray, "V", 50);
        keyCodeTranslator.addKeyAndValue(sparseArray, "W", 51);
        keyCodeTranslator.addKeyAndValue(sparseArray, "X", 52);
        keyCodeTranslator.addKeyAndValue(sparseArray, "Y", 53);
        keyCodeTranslator.addKeyAndValue(sparseArray, "Z", 54);
        keyCodeTranslator.addKeyAndValue(sparseArray, "COMMA", 55);
        keyCodeTranslator.addKeyAndValue(sparseArray, "PERIOD", 56);
        keyCodeTranslator.addKeyAndValue(sparseArray, "ALT LEFT", 57);
        keyCodeTranslator.addKeyAndValue(sparseArray, "ALT RIGHT", 58);
        keyCodeTranslator.addKeyAndValue(sparseArray, "SHIFT LEFT", 59);
        keyCodeTranslator.addKeyAndValue(sparseArray, "SHIFT RIGHT", 60);
        keyCodeTranslator.addKeyAndValue(sparseArray, "TAB", 61);
        keyCodeTranslator.addKeyAndValue(sparseArray, "SPACE", 62);
        keyCodeTranslator.addKeyAndValue(sparseArray, "SYM", 63);
        keyCodeTranslator.addKeyAndValue(sparseArray, "EXPLORER", 64);
        keyCodeTranslator.addKeyAndValue(sparseArray, "ENVELOPE", 65);
        keyCodeTranslator.addKeyAndValue(sparseArray, "ENTER", 66);
        keyCodeTranslator.addKeyAndValue(sparseArray, "DEL", 67);
        keyCodeTranslator.addKeyAndValue(sparseArray, "GRAVE", 68);
        keyCodeTranslator.addKeyAndValue(sparseArray, "MINUS", 69);
        keyCodeTranslator.addKeyAndValue(sparseArray, "EQUALS", 70);
        keyCodeTranslator.addKeyAndValue(sparseArray, "LEFT BRACKET", 71);
        keyCodeTranslator.addKeyAndValue(sparseArray, "RIGHT BRACKET", 72);
        keyCodeTranslator.addKeyAndValue(sparseArray, "BACKSLASH", 73);
        keyCodeTranslator.addKeyAndValue(sparseArray, "SEMICOLON", 74);
        keyCodeTranslator.addKeyAndValue(sparseArray, "APOSTROPHE", 75);
        keyCodeTranslator.addKeyAndValue(sparseArray, "SLASH", 76);
        keyCodeTranslator.addKeyAndValue(sparseArray, "AT", 77);
        keyCodeTranslator.addKeyAndValue(sparseArray, "NUM", 78);
        keyCodeTranslator.addKeyAndValue(sparseArray, "HEADSETHOOK", 79);
        keyCodeTranslator.addKeyAndValue(sparseArray, "FOCUS", 80);
        keyCodeTranslator.addKeyAndValue(sparseArray, "PLUS", 81);
        keyCodeTranslator.addKeyAndValue(sparseArray, "MENU", 82);
        keyCodeTranslator.addKeyAndValue(sparseArray, "NOTIFICATION", 83);
        keyCodeTranslator.addKeyAndValue(sparseArray, "SEARCH", 84);
        keyCodeTranslator.addKeyAndValue(sparseArray, "MEDIA PLAY PAUSE", 85);
        keyCodeTranslator.addKeyAndValue(sparseArray, "MEDIA STOP", 86);
        keyCodeTranslator.addKeyAndValue(sparseArray, "MEDIA NEXT", 87);
        keyCodeTranslator.addKeyAndValue(sparseArray, "MEDIA PREVIOUS", 88);
        keyCodeTranslator.addKeyAndValue(sparseArray, "MEDIA REWIND", 89);
        keyCodeTranslator.addKeyAndValue(sparseArray, "MEDIA FAST FORWARD", 90);
        keyCodeTranslator.addKeyAndValue(sparseArray, "MUTE", 91);
        keyCodeTranslator.addKeyAndValue(sparseArray, "PAGE UP", 92);
        keyCodeTranslator.addKeyAndValue(sparseArray, "PAGE DOWN", 93);
        keyCodeTranslator.addKeyAndValue(sparseArray, "PICTSYMBOLS", 94);
        keyCodeTranslator.addKeyAndValue(sparseArray, "SWITCH CHARSET", 95);
        keyCodeTranslator.addKeyAndValue(sparseArray, "BUTTON A", 96);
        keyCodeTranslator.addKeyAndValue(sparseArray, "BUTTON B", 97);
        keyCodeTranslator.addKeyAndValue(sparseArray, "BUTTON C", 98);
        keyCodeTranslator.addKeyAndValue(sparseArray, "BUTTON X", 99);
        keyCodeTranslator.addKeyAndValue(sparseArray, "BUTTON Y", 100);
        keyCodeTranslator.addKeyAndValue(sparseArray, "BUTTON Z", 101);
        keyCodeTranslator.addKeyAndValue(sparseArray, "BUTTON L1", 102);
        keyCodeTranslator.addKeyAndValue(sparseArray, "BUTTON R1", 103);
        keyCodeTranslator.addKeyAndValue(sparseArray, "BUTTON L2", 104);
        keyCodeTranslator.addKeyAndValue(sparseArray, "BUTTON R2", 105);
        keyCodeTranslator.addKeyAndValue(sparseArray, "BUTTON THUMBL", 106);
        keyCodeTranslator.addKeyAndValue(sparseArray, "BUTTON THUMBR", 107);
        keyCodeTranslator.addKeyAndValue(sparseArray, "BUTTON START", 108);
        keyCodeTranslator.addKeyAndValue(sparseArray, "BUTTON SELECT", 109);
        keyCodeTranslator.addKeyAndValue(sparseArray, "BUTTON MODE", 110);
        keyCodeTranslator.addKeyAndValue(sparseArray, "ESCAPE", 111);
        keyCodeTranslator.addKeyAndValue(sparseArray, "FORWARD DEL", 112);
        keyCodeTranslator.addKeyAndValue(sparseArray, "CTRL LEFT", 113);
        keyCodeTranslator.addKeyAndValue(sparseArray, "CTRL RIGHT", 114);
        keyCodeTranslator.addKeyAndValue(sparseArray, "CAPS LOCK", 115);
        keyCodeTranslator.addKeyAndValue(sparseArray, "SCROLL LOCK", 116);
        keyCodeTranslator.addKeyAndValue(sparseArray, "META LEFT", 117);
        keyCodeTranslator.addKeyAndValue(sparseArray, "META RIGHT", 118);
        keyCodeTranslator.addKeyAndValue(sparseArray, "FUNCTION", 119);
        keyCodeTranslator.addKeyAndValue(sparseArray, "SYSRQ", 120);
        keyCodeTranslator.addKeyAndValue(sparseArray, "BREAK", 121);
        keyCodeTranslator.addKeyAndValue(sparseArray, "MOVE HOME", 122);
        keyCodeTranslator.addKeyAndValue(sparseArray, "MOVE END", 123);
        keyCodeTranslator.addKeyAndValue(sparseArray, "INSERT", 124);
        keyCodeTranslator.addKeyAndValue(sparseArray, "FORWARD", 125);
        keyCodeTranslator.addKeyAndValue(sparseArray, "MEDIA PLAY", 126);
        keyCodeTranslator.addKeyAndValue(sparseArray, "MEDIA PAUSE", 127);
        keyCodeTranslator.addKeyAndValue(sparseArray, "MEDIA CLOSE", 128);
        keyCodeTranslator.addKeyAndValue(sparseArray, "MEDIA EJECT", 129);
        keyCodeTranslator.addKeyAndValue(sparseArray, "MEDIA RECORD", 130);
        keyCodeTranslator.addKeyAndValue(sparseArray, "F1", 131);
        keyCodeTranslator.addKeyAndValue(sparseArray, "F2", 132);
        keyCodeTranslator.addKeyAndValue(sparseArray, "F3", 133);
        keyCodeTranslator.addKeyAndValue(sparseArray, "F4", 134);
        keyCodeTranslator.addKeyAndValue(sparseArray, "F5", 135);
        keyCodeTranslator.addKeyAndValue(sparseArray, "F6", 136);
        keyCodeTranslator.addKeyAndValue(sparseArray, "F7", 137);
        keyCodeTranslator.addKeyAndValue(sparseArray, "F8", 138);
        keyCodeTranslator.addKeyAndValue(sparseArray, "F9", 139);
        keyCodeTranslator.addKeyAndValue(sparseArray, "F10", 140);
        keyCodeTranslator.addKeyAndValue(sparseArray, "F11", 141);
        keyCodeTranslator.addKeyAndValue(sparseArray, "F12", 142);
        keyCodeTranslator.addKeyAndValue(sparseArray, "NUM LOCK", 143);
        keyCodeTranslator.addKeyAndValue(sparseArray, "NUMPAD 0", 144);
        keyCodeTranslator.addKeyAndValue(sparseArray, "NUMPAD 1", 145);
        keyCodeTranslator.addKeyAndValue(sparseArray, "NUMPAD 2", 146);
        keyCodeTranslator.addKeyAndValue(sparseArray, "NUMPAD 3", 147);
        keyCodeTranslator.addKeyAndValue(sparseArray, "NUMPAD 4", 148);
        keyCodeTranslator.addKeyAndValue(sparseArray, "NUMPAD 5", 149);
        keyCodeTranslator.addKeyAndValue(sparseArray, "NUMPAD 6", 150);
        keyCodeTranslator.addKeyAndValue(sparseArray, "NUMPAD 7", 151);
        keyCodeTranslator.addKeyAndValue(sparseArray, "NUMPAD 8", ModuleDescriptor.MODULE_VERSION);
        keyCodeTranslator.addKeyAndValue(sparseArray, "NUMPAD 9", 153);
        keyCodeTranslator.addKeyAndValue(sparseArray, "NUMPAD DIVIDE", 154);
        keyCodeTranslator.addKeyAndValue(sparseArray, "NUMPAD MULTIPLY", 155);
        keyCodeTranslator.addKeyAndValue(sparseArray, "NUMPAD SUBTRACT", 156);
        keyCodeTranslator.addKeyAndValue(sparseArray, "NUMPAD ADD", 157);
        keyCodeTranslator.addKeyAndValue(sparseArray, "NUMPAD DOT", 158);
        keyCodeTranslator.addKeyAndValue(sparseArray, "NUMPAD COMMA", 159);
        keyCodeTranslator.addKeyAndValue(sparseArray, "NUMPAD ENTER", 160);
        keyCodeTranslator.addKeyAndValue(sparseArray, "NUMPAD EQUALS", 161);
        keyCodeTranslator.addKeyAndValue(sparseArray, "NUMPAD LEFT PAREN", 162);
        keyCodeTranslator.addKeyAndValue(sparseArray, "NUMPAD RIGHT PAREN", 163);
        keyCodeTranslator.addKeyAndValue(sparseArray, "VOLUME MUTE", 164);
        keyCodeTranslator.addKeyAndValue(sparseArray, "INFO", 165);
        keyCodeTranslator.addKeyAndValue(sparseArray, "CHANNEL UP", 166);
        keyCodeTranslator.addKeyAndValue(sparseArray, "CHANNEL DOWN", 167);
        keyCodeTranslator.addKeyAndValue(sparseArray, "ZOOM IN", 168);
        keyCodeTranslator.addKeyAndValue(sparseArray, "ZOOM OUT", 169);
        keyCodeTranslator.addKeyAndValue(sparseArray, "TV", 170);
        keyCodeTranslator.addKeyAndValue(sparseArray, "WINDOW", 171);
        keyCodeTranslator.addKeyAndValue(sparseArray, "GUIDE", 172);
        keyCodeTranslator.addKeyAndValue(sparseArray, "DVR", 173);
        keyCodeTranslator.addKeyAndValue(sparseArray, "BOOKMARK", 174);
        keyCodeTranslator.addKeyAndValue(sparseArray, "CAPTIONS", 175);
        keyCodeTranslator.addKeyAndValue(sparseArray, "SETTINGS", 176);
        keyCodeTranslator.addKeyAndValue(sparseArray, "TV POWER", 177);
        keyCodeTranslator.addKeyAndValue(sparseArray, "TV IN", 178);
        keyCodeTranslator.addKeyAndValue(sparseArray, "STB POWER", 179);
        keyCodeTranslator.addKeyAndValue(sparseArray, "STB IN", 180);
        keyCodeTranslator.addKeyAndValue(sparseArray, "AVR POWER", 181);
        keyCodeTranslator.addKeyAndValue(sparseArray, "AVR IN", 182);
        keyCodeTranslator.addKeyAndValue(sparseArray, "PROG RED", 183);
        keyCodeTranslator.addKeyAndValue(sparseArray, "PROG GREEN", 184);
        keyCodeTranslator.addKeyAndValue(sparseArray, "PROG YELLOW", 185);
        keyCodeTranslator.addKeyAndValue(sparseArray, "PROG BLUE", 186);
        keyCodeTranslator.addKeyAndValue(sparseArray, "APP SWITCH", 187);
        keyCodeTranslator.addKeyAndValue(sparseArray, "BUTTON APP 1", 188);
        keyCodeTranslator.addKeyAndValue(sparseArray, "BUTTON APP 2", 189);
        keyCodeTranslator.addKeyAndValue(sparseArray, "BUTTON APP 3", 190);
        keyCodeTranslator.addKeyAndValue(sparseArray, "BUTTON APP 4", 191);
        keyCodeTranslator.addKeyAndValue(sparseArray, "BUTTON APP 5", 192);
        keyCodeTranslator.addKeyAndValue(sparseArray, "BUTTON APP 6", 193);
        keyCodeTranslator.addKeyAndValue(sparseArray, "BUTTON APP 7", 194);
        keyCodeTranslator.addKeyAndValue(sparseArray, "BUTTON APP 8", 195);
        keyCodeTranslator.addKeyAndValue(sparseArray, "BUTTON APP 9", 196);
        keyCodeTranslator.addKeyAndValue(sparseArray, "BUTTON APP 10", 197);
        keyCodeTranslator.addKeyAndValue(sparseArray, "BUTTON APP 11", 198);
        keyCodeTranslator.addKeyAndValue(sparseArray, "BUTTON APP 12", 199);
        keyCodeTranslator.addKeyAndValue(sparseArray, "BUTTON APP 13", 200);
        keyCodeTranslator.addKeyAndValue(sparseArray, "BUTTON APP 14", 201);
        keyCodeTranslator.addKeyAndValue(sparseArray, "BUTTON APP 15", 202);
        keyCodeTranslator.addKeyAndValue(sparseArray, "BUTTON APP 16", 203);
        keyCodeTranslator.addKeyAndValue(sparseArray, "LANGUAGE SWITCH", 204);
        keyCodeTranslator.addKeyAndValue(sparseArray, "MANNER MODE", 205);
        keyCodeTranslator.addKeyAndValue(sparseArray, "3D MODE", 206);
        keyCodeTranslator.addKeyAndValue(sparseArray, "CONTACTS", 207);
        keyCodeTranslator.addKeyAndValue(sparseArray, "CALENDAR", 208);
        keyCodeTranslator.addKeyAndValue(sparseArray, "MUSIC", 209);
        keyCodeTranslator.addKeyAndValue(sparseArray, "CALCULATOR", 210);
        keyCodeTranslator.addKeyAndValue(sparseArray, "ZENKAKU HANKAKU", 211);
        keyCodeTranslator.addKeyAndValue(sparseArray, "EISU", 212);
        keyCodeTranslator.addKeyAndValue(sparseArray, "MUHENKAN", 213);
        keyCodeTranslator.addKeyAndValue(sparseArray, "HENKAN", 214);
        keyCodeTranslator.addKeyAndValue(sparseArray, "KATAKANA HIRAGANA", 215);
        keyCodeTranslator.addKeyAndValue(sparseArray, "YEN", 216);
        keyCodeTranslator.addKeyAndValue(sparseArray, "RO", 217);
        keyCodeTranslator.addKeyAndValue(sparseArray, "KANA", 218);
        keyCodeTranslator.addKeyAndValue(sparseArray, "ASSIST", 219);
        keyCodeTranslator.addKeyAndValue(sparseArray, "BRIGHTNESS DOWN", 220);
        keyCodeTranslator.addKeyAndValue(sparseArray, "BRIGHTNESS UP", 221);
        keyCodeTranslator.addKeyAndValue(sparseArray, "MEDIA AUDIO TRACK", 222);
        keyCodeTranslator.addKeyAndValue(sparseArray, "SLEEP", 223);
        keyCodeTranslator.addKeyAndValue(sparseArray, "WAKEUP", 224);
        keyCodeTranslator.addKeyAndValue(sparseArray, "PAIRING", 225);
        keyCodeTranslator.addKeyAndValue(sparseArray, "MEDIA TOP MENU", 226);
        keyCodeTranslator.addKeyAndValue(sparseArray, "11", 227);
        keyCodeTranslator.addKeyAndValue(sparseArray, "12", 228);
        keyCodeTranslator.addKeyAndValue(sparseArray, "LAST CHANNEL", 229);
        keyCodeTranslator.addKeyAndValue(sparseArray, "TV DATA SERVICE", 230);
        keyCodeTranslator.addKeyAndValue(sparseArray, "VOICE ASSIST", 231);
        keyCodeTranslator.addKeyAndValue(sparseArray, "TV RADIO SERVICE", 232);
        keyCodeTranslator.addKeyAndValue(sparseArray, "TV TELETEXT", 233);
        keyCodeTranslator.addKeyAndValue(sparseArray, "TV NUMBER ENTRY", 234);
        keyCodeTranslator.addKeyAndValue(sparseArray, "TV TERRESTRIAL ANALOG", 235);
        keyCodeTranslator.addKeyAndValue(sparseArray, "TV TERRESTRIAL DIGITAL", 236);
        keyCodeTranslator.addKeyAndValue(sparseArray, "TV SATELLITE", 237);
        keyCodeTranslator.addKeyAndValue(sparseArray, "TV SATELLITE BS", 238);
        keyCodeTranslator.addKeyAndValue(sparseArray, "TV SATELLITE CS", 239);
        keyCodeTranslator.addKeyAndValue(sparseArray, "TV SATELLITE SERVICE", 240);
        keyCodeTranslator.addKeyAndValue(sparseArray, "TV NETWORK", 241);
        keyCodeTranslator.addKeyAndValue(sparseArray, "TV ANTENNA CABLE", 242);
        keyCodeTranslator.addKeyAndValue(sparseArray, "TV IN HDMI 1 ", 243);
        keyCodeTranslator.addKeyAndValue(sparseArray, "TV IN HDMI 2 ", 244);
        keyCodeTranslator.addKeyAndValue(sparseArray, "TV IN HDMI 3 ", 245);
        keyCodeTranslator.addKeyAndValue(sparseArray, "TV IN HDMI 4 ", 246);
        keyCodeTranslator.addKeyAndValue(sparseArray, "TV IN COMPOSITE 1 ", 247);
        keyCodeTranslator.addKeyAndValue(sparseArray, "TV IN COMPOSITE 2 ", 248);
        keyCodeTranslator.addKeyAndValue(sparseArray, "TV IN COMPONENT 1 ", 249);
        keyCodeTranslator.addKeyAndValue(sparseArray, "TV IN COMPONENT 2 ", 250);
        keyCodeTranslator.addKeyAndValue(sparseArray, "TV IN VGA 1 ", 251);
        keyCodeTranslator.addKeyAndValue(sparseArray, "TV AUDIO DESCRIPTION", 252);
        keyCodeTranslator.addKeyAndValue(sparseArray, "TV AUDIO DESCRIPTION MIX UP", 253);
        keyCodeTranslator.addKeyAndValue(sparseArray, "TV AUDIO DESCRIPTION MIX DOWN", 254);
        keyCodeTranslator.addKeyAndValue(sparseArray, "TV ZOOM MODE", 255);
        keyCodeTranslator.addKeyAndValue(sparseArray, "TV CONTENTS MENU", 256);
        keyCodeTranslator.addKeyAndValue(sparseArray, "TV MEDIA CONTEXT MENU", 257);
        keyCodeTranslator.addKeyAndValue(sparseArray, "TV TIMER PROGRAMMING", 258);
        keyCodeTranslator.addKeyAndValue(sparseArray, "HELP", 259);
        keyCodeTranslator.addKeyAndValue(sparseArray, "NAVIGATE PREVIOUS", 260);
        keyCodeTranslator.addKeyAndValue(sparseArray, "NAVIGATE NEXT", 261);
        keyCodeTranslator.addKeyAndValue(sparseArray, "NAVIGATE IN", 262);
        keyCodeTranslator.addKeyAndValue(sparseArray, "NAVIGATE OUT", 263);
        keyCodeTranslator.addKeyAndValue(sparseArray, "STEM PRIMARY", 264);
        keyCodeTranslator.addKeyAndValue(sparseArray, "STEM 1", 265);
        keyCodeTranslator.addKeyAndValue(sparseArray, "STEM 2", 266);
        keyCodeTranslator.addKeyAndValue(sparseArray, "STEM 3", 267);
        keyCodeTranslator.addKeyAndValue(sparseArray, "DPAD UP LEFT", 268);
        keyCodeTranslator.addKeyAndValue(sparseArray, "DPAD DOWN LEFT", 269);
        keyCodeTranslator.addKeyAndValue(sparseArray, "DPAD UP RIGHT", 270);
        keyCodeTranslator.addKeyAndValue(sparseArray, "DPAD DOWN RIGHT", 271);
        keyCodeTranslator.addKeyAndValue(sparseArray, "MEDIA SKIP FORWARD", 272);
        keyCodeTranslator.addKeyAndValue(sparseArray, "MEDIA SKIP BACKWARD", 273);
        keyCodeTranslator.addKeyAndValue(sparseArray, "MEDIA STEP FORWARD", 274);
        keyCodeTranslator.addKeyAndValue(sparseArray, "MEDIA STEP BACKWARD", 275);
        keyCodeTranslator.addKeyAndValue(sparseArray, "SOFT SLEEP", 276);
        keyCodeTranslator.addKeyAndValue(sparseArray, "CUT", 277);
        keyCodeTranslator.addKeyAndValue(sparseArray, "COPY", 278);
        keyCodeTranslator.addKeyAndValue(sparseArray, "PASTE", 279);
        keyCodeTranslator.addKeyAndValue(sparseArray, "SYSTEM NAVIGATION UP", 280);
        keyCodeTranslator.addKeyAndValue(sparseArray, "SYSTEM NAVIGATION DOWN", 281);
        keyCodeTranslator.addKeyAndValue(sparseArray, "SYSTEM NAVIGATION LEFT", 282);
        keyCodeTranslator.addKeyAndValue(sparseArray, "SYSTEM NAVIGATION RIGHT", 283);
        keyCodeTranslator.addKeyAndValue(sparseArray, "ALL APPS", 284);
        keyCodeTranslator.addKeyAndValue(sparseArray, "REFRESH", 285);
        keyCodeTranslator.addKeyAndValue(sparseArray, "THUMBS UP", 286);
        keyCodeTranslator.addKeyAndValue(sparseArray, "THUMBS DOWN", 287);
        keyCodeTranslator.addKeyAndValue(sparseArray, "PROFILE SWITCH", 288);
        map = sparseArray;
    }

    private KeyCodeTranslator() {
    }

    private final void addKeyAndValue(SparseArray<String> sparseArray, String str, int i7) {
        sparseArray.put(i7, str);
    }

    public final String translate(int i7) {
        String str = map.get(i7, String.valueOf(i7));
        kotlin.jvm.internal.l.d(str, "get(...)");
        return str;
    }
}
